apiVersion: v2
name: kpow
description: Run Kpow for Apache Kafka in Kubernetes
type: application
version: 1.0.75
appVersion: "95.3"
keywords:
  - kafka
  - kafka-ui
  - kafka-connect
  - schema-registry
  - ksqldb
  - monitoring
home: "https://factorhouse.io/kpow"
sources:
  - "https://github.com/factorhouse/kpow"
  - "https://github.com/factorhouse/helm-charts/"
maintainers:
  - name: "Factor House Support"
    email: "support@factorhouse.io"
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9686853629F9810E63A72373BA3D0FAE1A26981F
    url: https://keybase.io/factorhouse/pgp_keys.asc
