apiVersion: v2
name: factor-platform
description: Run Factor Platform in Kubernetes
type: application
version: 0.0.1
appVersion: "95.1"
keywords:
  - kafka
  - kafka-ui
  - kafka-connect
  - schema-registry
  - ksqldb
  - flink
  - flink-ui
  - monitoring
  - control-plane
home: "https://factorhouse.io/products/factor-platform"
sources:
  - "https://github.com/factorhouse/factor-platform"
  - "https://github.com/factorhouse/helm-charts/"
maintainers:
  - name: "Factor House Support"
    email: "support@factorhouse.io"
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9686853629F9810E63A72373BA3D0FAE1A26981F
    url: https://keybase.io/factorhouse/pgp_keys.asc
